name: Preview PR Docs

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./out
          recurse: true
          front_page: README.md

      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          publish_dir: ./out
